export const cardNote =
    [
        { "id": 1, "name": "愚者" },
        { "id": 2, "name": "魔法師" },
        { "id": 3, "name": "女祭師" },
        { "id": 4, "name": "皇后" },
        { "id": 5, "name": "皇帝" },
        { "id": 6, "name": "教皇" },
        { "id": 7, "name": "戀人" },
        { "id": 8, "name": "戰車" },
        { "id": 9, "name": "力量" },
        { "id": 10, "name": "隱士" },
        { "id": 11, "name": "命運之輪" },
        { "id": 12, "name": "正義" },
        { "id": 13, "name": "倒吊人" },
        { "id": 14, "name": "死神" },
        { "id": 15, "name": "節制" },
        { "id": 16, "name": "塔" },
        { "id": 17, "name": "惡魔" },
        { "id": 18, "name": "星星" },
        { "id": 19, "name": "月亮" },
        { "id": 20, "name": "太陽" },
        { "id": 21, "name": "審判" },
        { "id": 22, "name": "世界" },
    ]